services:
  settings-backend:
    build:
      context: ../..
      dockerfile: docker/0.1.0/Dockerfile.backend
    container_name: maskservice-settings-backend
    ports:
      - "8108:8108"
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8108/health')"]
      interval: 30s
      timeout: 3s
      retries: 3

  settings-frontend:
    build:
      context: ../..
      dockerfile: docker/0.1.0/Dockerfile.frontend
    container_name: maskservice-settings-frontend
    ports:
      - "8208:80"
    depends_on:
      settings-backend:
        condition: service_healthy
