services:
  reports-backend:
    build:
      context: ../..
      dockerfile: docker/0.1.0/Dockerfile.backend
    container_name: maskservice-reports-backend
    ports:
      - "8208:8208"
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8208/health"]
      interval: 30s
      timeout: 3s
      retries: 3

  reports-frontend:
    build:
      context: ../..
      dockerfile: docker/0.1.0/Dockerfile.frontend
    container_name: maskservice-reports-frontend
    ports:
      - "8228:80"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 3s
      retries: 3
    depends_on:
      reports-backend:
        condition: service_healthy

  maskservice-reports-puppeteer:
    build:
      context: .
      dockerfile: Dockerfile.puppeteer
    container_name: maskservice-reports-puppeteer
    depends_on:
      reports-backend:
        condition: service_healthy
      reports-frontend:
        condition: service_started
    environment:
      - BACKEND_URL=http://reports-backend:8208
      - FRONTEND_URL=http://maskservice-reports-frontend
    volumes:
      - /tmp:/tmp
    command: ["sh", "-c", "sleep 10 && node puppeteer-test.js"]
