services:
  workshop-backend:
    build:
      context: ../..
      dockerfile: docker/0.1.0/Dockerfile.backend
    container_name: maskservice-workshop-backend
    ports:
      - "8211:8211"
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8211/health"]
      interval: 30s
      timeout: 3s
      retries: 3

  workshop-frontend:
    build:
      context: ../..
      dockerfile: docker/0.1.0/Dockerfile.frontend
    container_name: maskservice-workshop-frontend
    ports:
      - "8231:80"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 3s
      retries: 3
    depends_on:
      workshop-backend:
        condition: service_healthy

  maskservice-workshop-puppeteer:
    build:
      context: .
      dockerfile: Dockerfile.puppeteer
    container_name: maskservice-workshop-puppeteer
    depends_on:
      workshop-backend:
        condition: service_healthy
      workshop-frontend:
        condition: service_started
    environment:
      - BACKEND_URL=http://workshop-backend:8211
      - FRONTEND_URL=http://maskservice-workshop-frontend
    volumes:
      - /tmp:/tmp
    command: ["sh", "-c", "sleep 10 && node puppeteer-test.js"]
