version: '3.8'

services:
  login-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: maskservice-login-backend
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 30s
      timeout: 10s
      retries: 3

  login-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: maskservice-login-frontend
    ports:
      - "3001:80"
    depends_on:
      - login-backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: maskservice-login-network
