services:
  login-backend:
    build:
      context: ../..
      dockerfile: docker/0.1.0/Dockerfile.backend
    container_name: maskservice-login-backend
    ports:
      - "8201:8201"
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8201/health"]
      interval: 30s
      timeout: 3s
      retries: 3

  login-frontend:
    build:
      context: ../..
      dockerfile: docker/0.1.0/Dockerfile.frontend
    container_name: maskservice-login-frontend
    ports:
      - "8221:80"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 3s
      retries: 3
    depends_on:
      login-backend:
        condition: service_healthy

  # Advanced Frontend Testing Service
  login-frontend-tester:
    image: node:18-alpine
    container_name: maskservice-login-frontend-tester
    working_dir: /app
    volumes:
      - ./test-frontend.js:/app/test-frontend.js
    command: >
      sh -c "
        npm install -g puppeteer &&
        node test-frontend.js http://login-frontend:80/
      "
    depends_on:
      login-frontend:
        condition: service_healthy
    profiles:
      - testing
