services:
  service-backend:
    build:
      context: ../..
      dockerfile: docker/0.1.0/Dockerfile.backend
    container_name: maskservice-service-backend
    ports:
      - "8209:8209"
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8209/health"]
      interval: 30s
      timeout: 3s
      retries: 3

  service-frontend:
    build:
      context: ../..
      dockerfile: docker/0.1.0/Dockerfile.frontend
    container_name: maskservice-service-frontend
    ports:
      - "8229:80"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 3s
      retries: 3
    depends_on:
      service-backend:
        condition: service_healthy

  maskservice-service-puppeteer:
    build:
      context: .
      dockerfile: Dockerfile.puppeteer
    container_name: maskservice-service-puppeteer
    depends_on:
      service-backend:
        condition: service_healthy
      service-frontend:
        condition: service_started
    environment:
      - BACKEND_URL=http://service-backend:8209
      - FRONTEND_URL=http://maskservice-service-frontend
    volumes:
      - /tmp:/tmp
    command: ["sh", "-c", "sleep 10 && node puppeteer-test.js"]
